# Don't print a new line at the start of the prompt
add_newline = false

[character]
#symbol = "➜"


[time]
disabled = false
#format = "🕙[ %T ]"
#format = "%T "
#utc_time_offset = -5

[custom.rdshell]
when = """ test -n "$RCO_DEV_SUBSHELL" """
command = "echo \"$(nix-instantiate --eval -A device ${RCO_DEV_DIR}/workspace/.rco-dev.nix | jq -r '.')/$RCO_DEV_SUBSHELL\""

